version: '3'

services: 
  db:
    container_name: api_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: school-management
      POSTGRES_USER: school-management
      POSTGRES_DB: school-management
    volumes:
      - ./src/main/java/br/com/ufc/quixada/dspersist/schoolmanagement/repositories/postgres_data:/var/lib/postgresql/data